# Site settings
title: HEYANG LONG
description: Heyang Long's homepage
url: https://newtanc.github.io
jsurl: https://github.com/NewTanc/NewTanc.github.io
permalink: /:title

# User settings
username: Heyang Long
author-pic: face.jpg # your photo
user_description: I am a physics graduate student at <a target="_blank" href="https://physics.osu.edu/">The Ohio State University</a>, <a target="_blank" href="https://ccapp.osu.edu">Center for Cosmology and AstroParticle Physics (CCAPP)</a>. I work with <a target="_blank" href="https://hirata10.github.io">Prof. Christopher Hirata</a> on a variety of topics in cosmology, such as HI 21cm transition, weak gravitational lensing and reionization, to theoretically study the large-scale structure and evolution of the Universe.  I received my B.S. at Physics in <a target="_blank" href="https://www.nju.edu.cn/EN/">Nanjing University</a>. 

In leisure time, I am enthusiastic about photography, stargazing, cooking spicy food and petting my sweet little cat Batian (霸天).

user_title: Heyang
email: long.1697@osu.edu
github_username:  newtanc


# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Google-analytics
#google-analytics:
#  id: ""

# exclude: ['package.json', 'src' , 'node_modules']

mathjax:   true  # enables support for mathjax - set to 'false' to disable

include:   [ "robots.txt" ]
exclude:   [ 'package.json', 'src' , 'node_modules',"LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins_dir:
  - jekyll-sitemap

nav:
  - GALLERY: "/gallery/"  
  - BLOG: "/blog"
#  - ABOUT: "https://sunbliss.github.io/photorama/about/"

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
