# Site settings
title: HE-YANG LONG
description: Heyang Long's homepage
url: https://newtanc.github.io
jsurl: https://github.com/NewTanc/NewTanc.github.io
permalink: /:title

# User settings
username: Heyang Long
author-pic: face.jpg # your photo
user_description: Physics graduate student at <a target="_blank" href="https://physics.osu.edu/">Ohio State University</a>. Got my BSc degree in Physics from <a target="_blank" href="https://www.nju.edu.cn/EN/">Nanjing University</a>. Interested in theoretical physics, especially particle physics and cosmology. Lakers fan. A lover of hiking, poem and photography. Extremely good at eating spicy food and <a target="_blank" href="http://image.baidu.com/search/index?tn=baiduimage&ps=1&ct=201326592&lm=-1&cl=2&nc=1&ie=utf-8&word=%E5%9B%9B%E5%B7%9D%E7%81%AB%E9%94%85">Sichuan hot pot</a> is my favorite. 
user_title: Physics Student
email: long.1697@osu.edu
wechat_username: newtanc
github_username:  newtanc
facebook_usermame: heyanglong

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Google-analytics
#google-analytics:
#  id: ""

# exclude: ['package.json', 'src' , 'node_modules']

mathjax:   true  # enables support for mathjax - set to 'false' to disable

include:   [ "robots.txt" ]
exclude:   [ 'package.json', 'src' , 'node_modules',"LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins_dir:
  - jekyll-sitemap

nav:
  - GALLERY: "/gallery/"  
  - BLOG: "/blog/"
#  - ABOUT: "https://sunbliss.github.io/photorama/about/"

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
