# Site settings
title: Heyang Long
description: Heyang Long's homepage
url: https://cosmosheep.github.io
jsurl: https://github.com/CosmoSheep/cosmosheep.github.io
permalink: /:title

# User settings
username: Heyang Long
author-pic: face.jpg # your photo
user_description: >
  I draw energy from deep thinking and learning — most often through applied math, physics, and philosophy. Lately, this curiosity has led me toward quantitative finance and AI. From 2018 to 2024, I studied Cosmology with Christopher Hirata at OSU; explore my <a target="_blank" href="https://inspirehep.net/authors/1774798">publications</a> here.<br><br>
  My favorite university on this planet is Nanjing University. I love exploring mountains — hiking in the summer and snowboarding in the winter. I was born and raised in Sichuan, China. I am also a decent cook, especially when it comes to spicy food. My go-to Sichuan spot in NYC is <strong>Lunar</strong>. Drawn to visual arts, I spend much of my free time photographing moments and wandering through various museums and galleries worldwide. Earning an art degree is still on my bucket list. I am also a caffeine-holic, <strong>Devoción</strong> is my favorite coffee shop in NYC.<br><br>
  I read Hermann Hesse, Jorge Luis Borges, Chizuko Ueno, Cao Xueqin, and Yu Xiuhua.<br><br>
  I have a sweet white cat Batian (霸天), who’s been my companion since 2020 in Ohio.<br><br>
  I care deeply about inclusiveness and equity for gender minorities and the LGBTQ+ community. <br><br>
  If you're ever up for a coffee chat in NYC, feel free to <a href="mailto:hylong1024@gmail.com">reach out</a>.

user_title: Heyang
email: hylong1024@gmail.com
github_username:  CosmoSheep


# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Google-analytics
google-analytics: G-SB6S7SZ5MS
  # id: 

# exclude: ['package.json', 'src' , 'node_modules']

mathjax:   true  # enables support for mathjax - set to 'false' to disable

include:   [ "robots.txt" ]
exclude:   [ 'package.json', 'src' , 'node_modules',"LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins_dir:
  - jekyll-sitemap

nav:
  - GALLERY: "/gallery/"  
  - BLOG: "/blog"
#  - ABOUT: "https://sunbliss.github.io/photorama/about/"

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
